import { TerrainType } from '../../terrains.config.ts';
import { createAnimalSpecies } from '../animal.defaults.ts';
import { AnimalSpeciesDefinition } from '../animal.types.ts';

export const BIRD_ANIMAL_SPECIES: readonly AnimalSpeciesDefinition[] = [
  createAnimalSpecies({
    id: 'sparrow',
    name: 'Chim sẻ',
    group: 'bird',
    description: 'Loài chim nhỏ kiếm hạt cỏ và sâu bọ trên mặt đất khắp các vùng đồng bằng.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST],
    spawnWeight: 18,
    lifespanYears: 5,
    adultAgeYears: 0.5,
    reproductionCooldownDays: 20,
    bodyShape: 'avian',
    primaryColor: '#a16207',
    secondaryColor: '#d6d3d1',
  }),
  createAnimalSpecies({
    id: 'pigeon',
    name: 'Bồ câu',
    group: 'bird',
    description: 'Chim ăn hạt hiền lành, thường đi kiếm ăn theo bầy trên đất trống và sườn đồi.',
    sizePreset: 'small',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU],
    spawnWeight: 15,
    lifespanYears: 7,
    adultAgeYears: 0.7,
    reproductionCooldownDays: 24,
    bodyShape: 'avian',
    primaryColor: '#94a3b8',
    secondaryColor: '#475569',
  }),
  createAnimalSpecies({
    id: 'crow',
    name: 'Quạ',
    group: 'bird',
    description: 'Loài chim lông đen ăn tạp, tìm cả quả rụng, chuột nhỏ lẫn xác thú.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST, TerrainType.SWAMP],
    spawnWeight: 12,
    preySpeciesIds: ['house_mouse', 'field_rat', 'lizard'],
    lifespanYears: 10,
    adultAgeYears: 1.0,
    reproductionCooldownDays: 30,
    bodyShape: 'avian',
    primaryColor: '#1e293b',
    secondaryColor: '#0f172a',
  }),
  createAnimalSpecies({
    id: 'owl',
    name: 'Cú mèo',
    group: 'bird',
    description: 'Chim săn mồi vùng rừng đồi, chuyên bắt chuột, sóc, rắn nhỏ và chim sẻ.',
    sizePreset: 'small',
    diet: 'carnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 8,
    preySpeciesIds: ['house_mouse', 'field_rat', 'squirrel', 'sparrow', 'lizard', 'snake'],
    lifespanYears: 11,
    adultAgeYears: 1.0,
    reproductionCooldownDays: 32,
    bodyShape: 'avian',
    primaryColor: '#78350f',
    secondaryColor: '#fef3c7',
  }),
  createAnimalSpecies({
    id: 'eagle',
    name: 'Đại bàng',
    group: 'bird',
    description: 'Chim săn mồi dũng mãnh vùng núi cao và thảo nguyên, săn thỏ, rắn và các loài chim nhỏ.',
    sizePreset: 'small',
    diet: 'carnivore',
    habitats: [TerrainType.MOUNTAIN, TerrainType.PLATEAU, TerrainType.HILL],
    spawnWeight: 6,
    preySpeciesIds: [
      'rabbit',
      'house_mouse',
      'field_rat',
      'squirrel',
      'snake',
      'lizard',
      'chicken',
      'duck',
      'sparrow',
      'pigeon',
      'pheasant',
    ],
    lifespanYears: 16,
    adultAgeYears: 1.8,
    reproductionCooldownDays: 45,
    bodyShape: 'avian',
    primaryColor: '#451a03',
    secondaryColor: '#f8fafc',
  }),
  createAnimalSpecies({
    id: 'peafowl',
    name: 'Công',
    group: 'bird',
    description: 'Loài chim có bộ lông rực rỡ sống ở rừng thưa và đồi cỏ, ăn hạt và mầm cây.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.PLAIN],
    spawnWeight: 7,
    lifespanYears: 14,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 40,
    bodyShape: 'avian',
    primaryColor: '#0284c7',
    secondaryColor: '#10b981',
  }),
  createAnimalSpecies({
    id: 'pheasant',
    name: 'Chim trĩ',
    group: 'bird',
    description: 'Chim rừng chạy bộ nhanh trên mặt đất, kiếm hạt dại và chồi cỏ nơi đồi rừng.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.PLAIN],
    spawnWeight: 11,
    lifespanYears: 9,
    adultAgeYears: 0.9,
    reproductionCooldownDays: 28,
    bodyShape: 'avian',
    primaryColor: '#b91c1c',
    secondaryColor: '#f59e0b',
  }),
];
