import { TerrainType } from '../../terrains.config.ts';
import { createAnimalSpecies } from '../animal.defaults.ts';
import { AnimalSpeciesDefinition } from '../animal.types.ts';

export const DOMESTIC_ANIMAL_SPECIES: readonly AnimalSpeciesDefinition[] = [
  createAnimalSpecies({
    id: 'dog',
    name: 'Chó',
    group: 'domestic',
    description: 'Loài thú quen sống quanh thôn xóm và đồng cỏ, lanh lợi và săn bắt thú nhỏ.',
    sizePreset: 'medium',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU],
    spawnWeight: 10,
    preySpeciesIds: ['rabbit', 'house_mouse', 'field_rat', 'squirrel'],
    lifespanYears: 14,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 45,
    bodyShape: 'quadruped',
    primaryColor: '#b47b48',
    secondaryColor: '#6e4726',
  }),
  createAnimalSpecies({
    id: 'cat',
    name: 'Mèo',
    group: 'domestic',
    description: 'Loài thú nhỏ nhanh nhẹn, chuyên rình bắt chuột, chim sẻ và thằn lằn.',
    sizePreset: 'medium',
    diet: 'carnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL],
    spawnWeight: 10,
    preySpeciesIds: ['house_mouse', 'field_rat', 'sparrow', 'pigeon', 'squirrel', 'lizard'],
    lifespanYears: 15,
    adultAgeYears: 1.2,
    reproductionCooldownDays: 40,
    bodyShape: 'small_mammal',
    primaryColor: '#d99b52',
    secondaryColor: '#f5e1c8',
  }),
  createAnimalSpecies({
    id: 'water_buffalo',
    name: 'Trâu',
    group: 'domestic',
    description: 'Thú ăn cỏ vóc dáng vạm vỡ, ưa vùng đồng bằng ẩm và ven đầm lầy.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.SWAMP],
    spawnWeight: 8,
    lifespanYears: 22,
    adultAgeYears: 3,
    reproductionCooldownDays: 75,
    bodyShape: 'large_ungulate',
    primaryColor: '#4b5563',
    secondaryColor: '#1f2937',
  }),
  createAnimalSpecies({
    id: 'cattle',
    name: 'Bò',
    group: 'domestic',
    description: 'Loài thú ăn cỏ hiền lành, thường kiếm ăn theo đàn trên đồng cỏ và đồi thấp.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU],
    spawnWeight: 9,
    lifespanYears: 20,
    adultAgeYears: 2.5,
    reproductionCooldownDays: 70,
    bodyShape: 'large_ungulate',
    primaryColor: '#9a5b32',
    secondaryColor: '#5c3419',
  }),
  createAnimalSpecies({
    id: 'pig',
    name: 'Lợn',
    group: 'domestic',
    description: 'Thú ăn tạp dễ thích nghi, tìm rễ cây và thức ăn rơi vãi trên mặt đất.',
    sizePreset: 'medium',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL],
    spawnWeight: 10,
    lifespanYears: 15,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 45,
    bodyShape: 'quadruped',
    primaryColor: '#e6a6b0',
    secondaryColor: '#b8737e',
  }),
  createAnimalSpecies({
    id: 'goat',
    name: 'Dê',
    group: 'domestic',
    description: 'Thú ăn cỏ leo trèo giỏi, thích gặm chồi non trên đồi núi và cao nguyên.',
    sizePreset: 'medium',
    diet: 'herbivore',
    habitats: [TerrainType.HILL, TerrainType.MOUNTAIN, TerrainType.PLATEAU],
    spawnWeight: 9,
    lifespanYears: 14,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 50,
    bodyShape: 'quadruped',
    primaryColor: '#d1c7b7',
    secondaryColor: '#78716c',
  }),
  createAnimalSpecies({
    id: 'sheep',
    name: 'Cừu',
    group: 'domestic',
    description: 'Loài thú ăn cỏ bộ lông dày, kiếm ăn hiền hòa trên thảo nguyên và đồi cỏ.',
    sizePreset: 'medium',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU],
    spawnWeight: 9,
    lifespanYears: 13,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 50,
    bodyShape: 'quadruped',
    primaryColor: '#f3f4f6',
    secondaryColor: '#9ca3af',
  }),
  createAnimalSpecies({
    id: 'horse',
    name: 'Ngựa',
    group: 'domestic',
    description: 'Thú ăn cỏ chân dài chạy rất nhanh trên các vùng đồng bằng và cao nguyên rộng mở.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.PLATEAU, TerrainType.HILL],
    spawnWeight: 7,
    moveSpeed: 55,
    lifespanYears: 25,
    adultAgeYears: 3,
    reproductionCooldownDays: 80,
    bodyShape: 'large_ungulate',
    primaryColor: '#8b4513',
    secondaryColor: '#3b1d08',
  }),
  createAnimalSpecies({
    id: 'donkey',
    name: 'Lừa',
    group: 'domestic',
    description: 'Thú ăn cỏ bền bỉ, chịu đựng tốt địa hình đồi đá và cao nguyên khô cằn.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU],
    spawnWeight: 7,
    lifespanYears: 24,
    adultAgeYears: 2.5,
    reproductionCooldownDays: 75,
    bodyShape: 'large_ungulate',
    primaryColor: '#78716c',
    secondaryColor: '#44403c',
  }),
  createAnimalSpecies({
    id: 'chicken',
    name: 'Gà',
    group: 'domestic',
    description: 'Gia cầm nhỏ kiếm hạt cây và côn trùng trên mặt đất.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL],
    spawnWeight: 14,
    lifespanYears: 8,
    adultAgeYears: 0.8,
    reproductionCooldownDays: 28,
    bodyShape: 'avian',
    primaryColor: '#d97706',
    secondaryColor: '#991b1b',
  }),
  createAnimalSpecies({
    id: 'duck',
    name: 'Vịt',
    group: 'domestic',
    description: 'Thủy cầm kiếm ăn trên đồng bằng ẩm thấp và vùng đất ngập nước.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.SWAMP],
    spawnWeight: 12,
    lifespanYears: 9,
    adultAgeYears: 0.9,
    reproductionCooldownDays: 30,
    bodyShape: 'avian',
    primaryColor: '#a16207',
    secondaryColor: '#15803d',
  }),
  createAnimalSpecies({
    id: 'goose',
    name: 'Ngỗng',
    group: 'domestic',
    description: 'Gia cầm cổ dài ăn cỏ non và hạt thực vật trên bãi cỏ bằng phẳng.',
    sizePreset: 'small',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.SWAMP],
    spawnWeight: 10,
    lifespanYears: 12,
    adultAgeYears: 1.0,
    reproductionCooldownDays: 35,
    bodyShape: 'avian',
    primaryColor: '#f8fafc',
    secondaryColor: '#f59e0b',
  }),
];
