import { TerrainType } from '../../terrains.config.ts';
import { createAnimalSpecies } from '../animal.defaults.ts';
import { AnimalSpeciesDefinition } from '../animal.types.ts';

export const LARGE_MAMMAL_ANIMAL_SPECIES: readonly AnimalSpeciesDefinition[] = [
  createAnimalSpecies({
    id: 'spotted_deer',
    name: 'Hươu sao',
    group: 'large_mammal',
    description: 'Thú ăn cỏ bộ lông đốm trắng thanh thoát, thường gặm cỏ ven rừng và đồng bằng.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST],
    spawnWeight: 10,
    lifespanYears: 18,
    adultAgeYears: 2.0,
    reproductionCooldownDays: 60,
    bodyShape: 'large_ungulate',
    primaryColor: '#c27838',
    secondaryColor: '#fef3c7',
  }),
  createAnimalSpecies({
    id: 'sambar_deer',
    name: 'Nai',
    group: 'large_mammal',
    description: 'Loài thú ăn cỏ có sừng nhánh lớn, sống trong rừng sâu và sườn đồi.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 8,
    lifespanYears: 20,
    adultAgeYears: 2.5,
    reproductionCooldownDays: 65,
    bodyShape: 'large_ungulate',
    primaryColor: '#7c4a24',
    secondaryColor: '#45260e',
  }),
  createAnimalSpecies({
    id: 'muntjac',
    name: 'Hoẵng',
    group: 'large_mammal',
    description: 'Loài thú ăn lá rừng nhút nhát, chạy rất nhanh khi đánh hơi thấy hổ báo.',
    sizePreset: 'large',
    diet: 'herbivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL],
    spawnWeight: 10,
    lifespanYears: 15,
    adultAgeYears: 1.8,
    reproductionCooldownDays: 55,
    bodyShape: 'large_ungulate',
    primaryColor: '#b45309',
    secondaryColor: '#78350f',
  }),
  createAnimalSpecies({
    id: 'wild_boar',
    name: 'Lợn rừng',
    group: 'large_mammal',
    description: 'Thú rừng ăn tạp có cặp nanh cứng, đào củ rễ và ăn cả rắn rết nhỏ.',
    sizePreset: 'large',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.SWAMP],
    spawnWeight: 9,
    preySpeciesIds: ['house_mouse', 'field_rat', 'snake', 'lizard'],
    lifespanYears: 16,
    adultAgeYears: 2.0,
    reproductionCooldownDays: 55,
    bodyShape: 'quadruped',
    primaryColor: '#44403c',
    secondaryColor: '#1c1917',
  }),
  createAnimalSpecies({
    id: 'wolf',
    name: 'Sói',
    group: 'large_mammal',
    description: 'Thú săn mồi dẻo dai tốc độ cao, chuyên truy đuổi hươu nai, thỏ và gia súc.',
    sizePreset: 'large',
    diet: 'carnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST, TerrainType.PLATEAU, TerrainType.MOUNTAIN],
    spawnWeight: 6,
    moveSpeed: 55,
    preySpeciesIds: [
      'rabbit',
      'spotted_deer',
      'sambar_deer',
      'muntjac',
      'sheep',
      'goat',
      'pig',
      'chicken',
      'duck',
      'goose',
      'pheasant',
    ],
    lifespanYears: 16,
    adultAgeYears: 2.0,
    reproductionCooldownDays: 65,
    bodyShape: 'quadruped',
    primaryColor: '#64748b',
    secondaryColor: '#334155',
  }),
  createAnimalSpecies({
    id: 'tiger',
    name: 'Hổ',
    group: 'large_mammal',
    description: 'Chúa sơn lâm dũng mãnh, săn các loài thú ăn cỏ lớn trong rừng rậm và núi đồi.',
    sizePreset: 'large',
    diet: 'carnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 4,
    preySpeciesIds: [
      'spotted_deer',
      'sambar_deer',
      'muntjac',
      'wild_boar',
      'water_buffalo',
      'cattle',
      'pig',
      'goat',
      'sheep',
      'horse',
      'donkey',
      'monkey',
    ],
    lifespanYears: 22,
    adultAgeYears: 3.0,
    reproductionCooldownDays: 85,
    bodyShape: 'quadruped',
    primaryColor: '#f97316',
    secondaryColor: '#1e293b',
  }),
  createAnimalSpecies({
    id: 'leopard',
    name: 'Báo hoa mai',
    group: 'large_mammal',
    description: 'Thú săn mồi cực kỳ nhanh nhẹn, phục kích con mồi từ bìa rừng và sườn núi.',
    sizePreset: 'large',
    diet: 'carnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 5,
    moveSpeed: 55,
    preySpeciesIds: [
      'rabbit',
      'spotted_deer',
      'muntjac',
      'wild_boar',
      'monkey',
      'goat',
      'sheep',
      'pig',
      'peafowl',
      'pheasant',
    ],
    lifespanYears: 20,
    adultAgeYears: 2.5,
    reproductionCooldownDays: 80,
    bodyShape: 'quadruped',
    primaryColor: '#eab308',
    secondaryColor: '#27272a',
  }),
  createAnimalSpecies({
    id: 'black_bear',
    name: 'Gấu ngựa',
    group: 'large_mammal',
    description: 'Thú lớn ăn tạp vùng rừng núi, vừa kiếm quả rừng vừa săn thú cỡ vừa.',
    sizePreset: 'large',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.MOUNTAIN, TerrainType.HILL],
    spawnWeight: 4,
    preySpeciesIds: ['spotted_deer', 'muntjac', 'wild_boar', 'pig', 'sheep', 'goat'],
    lifespanYears: 25,
    adultAgeYears: 3.5,
    reproductionCooldownDays: 90,
    bodyShape: 'quadruped',
    primaryColor: '#1f2937',
    secondaryColor: '#fef08a',
  }),
  createAnimalSpecies({
    id: 'elephant',
    name: 'Voi',
    group: 'large_mammal',
    description: 'Thú ăn cỏ khổng lồ sức phòng ngự rất cao, di chuyển chậm rãi qua rừng thưa và đồng cỏ.',
    sizePreset: 'huge',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.DENSE_FOREST, TerrainType.PLATEAU],
    spawnWeight: 3,
    lifespanYears: 55,
    adultAgeYears: 8.0,
    reproductionCooldownDays: 140,
    bodyShape: 'large_ungulate',
    primaryColor: '#6b7280',
    secondaryColor: '#4b5563',
  }),
  createAnimalSpecies({
    id: 'rhinoceros',
    name: 'Tê giác',
    group: 'large_mammal',
    description: 'Thú ăn cỏ da dày có sừng cứng, sống ở vùng đầm lầy, đồng cỏ và rừng rậm.',
    sizePreset: 'huge',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.SWAMP, TerrainType.DENSE_FOREST],
    spawnWeight: 3,
    lifespanYears: 45,
    adultAgeYears: 6.0,
    reproductionCooldownDays: 120,
    bodyShape: 'large_ungulate',
    primaryColor: '#52525b',
    secondaryColor: '#3f3f46',
  }),
];
