import { TerrainType } from '../../terrains.config.ts';
import { createAnimalSpecies } from '../animal.defaults.ts';
import { AnimalSpeciesDefinition } from '../animal.types.ts';

export const REPTILE_ANIMAL_SPECIES: readonly AnimalSpeciesDefinition[] = [
  createAnimalSpecies({
    id: 'snake',
    name: 'Rắn',
    group: 'reptile',
    description: 'Loài bò sát không chân trườn trên mặt đất, săn chuột, thỏ con, chim sẻ và thằn lằn.',
    sizePreset: 'small',
    diet: 'carnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.SWAMP, TerrainType.HILL, TerrainType.PLAIN],
    spawnWeight: 10,
    preySpeciesIds: [
      'house_mouse',
      'field_rat',
      'squirrel',
      'rabbit',
      'sparrow',
      'pigeon',
      'lizard',
      'chicken',
    ],
    lifespanYears: 10,
    adultAgeYears: 1.2,
    reproductionCooldownDays: 35,
    bodyShape: 'serpent',
    primaryColor: '#15803d',
    secondaryColor: '#bef264',
  }),
  createAnimalSpecies({
    id: 'lizard',
    name: 'Thằn lằn',
    group: 'reptile',
    description: 'Bò sát nhỏ bò nhanh trên mỏm đá và bìa rừng, kiếm ăn trên mặt đất.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.PLATEAU, TerrainType.DENSE_FOREST],
    spawnWeight: 14,
    lifespanYears: 6,
    adultAgeYears: 0.7,
    reproductionCooldownDays: 22,
    bodyShape: 'serpent',
    primaryColor: '#65a30d',
    secondaryColor: '#a3e635',
  }),
  createAnimalSpecies({
    id: 'tortoise',
    name: 'Rùa cạn',
    group: 'reptile',
    description: 'Bò sát có mai cứng di chuyển rất chậm nhưng sống thọ, ăn lá cây và cỏ mềm.',
    sizePreset: 'small',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.SWAMP, TerrainType.DENSE_FOREST, TerrainType.HILL],
    spawnWeight: 8,
    moveSpeed: 10,
    lifespanYears: 60,
    adultAgeYears: 6.0,
    reproductionCooldownDays: 90,
    bodyShape: 'shelled_reptile',
    primaryColor: '#3f6212',
    secondaryColor: '#713f12',
  }),
];
