import { TerrainType } from '../../terrains.config.ts';
import { createAnimalSpecies } from '../animal.defaults.ts';
import { AnimalSpeciesDefinition } from '../animal.types.ts';

export const SMALL_MAMMAL_ANIMAL_SPECIES: readonly AnimalSpeciesDefinition[] = [
  createAnimalSpecies({
    id: 'rabbit',
    name: 'Thỏ',
    group: 'small_mammal',
    description: 'Thú ăn cỏ tai dài, cảnh giác cao và lập tức bỏ chạy khi phát hiện thú săn mồi.',
    sizePreset: 'medium',
    diet: 'herbivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST],
    spawnWeight: 16,
    lifespanYears: 8,
    adultAgeYears: 0.8,
    reproductionCooldownDays: 25,
    bodyShape: 'small_mammal',
    primaryColor: '#e5e7eb',
    secondaryColor: '#f9a8d4',
  }),
  createAnimalSpecies({
    id: 'house_mouse',
    name: 'Chuột nhà',
    group: 'small_mammal',
    description: 'Loài gặm nhấm nhỏ bé ăn tạp, sinh sôi nhanh trên đồng bằng và đồi thấp.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL],
    spawnWeight: 18,
    lifespanYears: 4,
    adultAgeYears: 0.4,
    reproductionCooldownDays: 18,
    bodyShape: 'small_mammal',
    primaryColor: '#6b7280',
    secondaryColor: '#374151',
  }),
  createAnimalSpecies({
    id: 'field_rat',
    name: 'Chuột đồng',
    group: 'small_mammal',
    description: 'Chuột hoang sống ngoài đồng cỏ và đầm lầy, nguồn thức ăn của nhiều loài săn mồi.',
    sizePreset: 'small',
    diet: 'omnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.SWAMP],
    spawnWeight: 18,
    lifespanYears: 5,
    adultAgeYears: 0.5,
    reproductionCooldownDays: 20,
    bodyShape: 'small_mammal',
    primaryColor: '#785a3c',
    secondaryColor: '#4a3520',
  }),
  createAnimalSpecies({
    id: 'squirrel',
    name: 'Sóc',
    group: 'small_mammal',
    description: 'Thú nhỏ đuôi xù nhanh nhẹn, chuyên nhặt hạt dẻ và quả rừng.',
    sizePreset: 'small',
    diet: 'herbivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL],
    spawnWeight: 15,
    lifespanYears: 7,
    adultAgeYears: 0.8,
    reproductionCooldownDays: 26,
    bodyShape: 'small_mammal',
    primaryColor: '#b45309',
    secondaryColor: '#78350f',
  }),
  createAnimalSpecies({
    id: 'porcupine',
    name: 'Nhím',
    group: 'small_mammal',
    description: 'Thú ăn củ quả có lớp lông gai cứng bảo vệ cơ thể nơi bìa rừng.',
    sizePreset: 'medium',
    diet: 'herbivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 9,
    lifespanYears: 12,
    adultAgeYears: 1.5,
    reproductionCooldownDays: 45,
    bodyShape: 'small_mammal',
    primaryColor: '#57534e',
    secondaryColor: '#d6d3d1',
  }),
  createAnimalSpecies({
    id: 'civet',
    name: 'Chồn hương',
    group: 'small_mammal',
    description: 'Thú ăn tạp thân thon dài, vừa ăn quả ngọt vừa săn chuột và bò sát nhỏ.',
    sizePreset: 'medium',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL],
    spawnWeight: 8,
    preySpeciesIds: ['house_mouse', 'field_rat', 'sparrow', 'lizard'],
    lifespanYears: 12,
    adultAgeYears: 1.4,
    reproductionCooldownDays: 42,
    bodyShape: 'small_mammal',
    primaryColor: '#716254',
    secondaryColor: '#292524',
  }),
  createAnimalSpecies({
    id: 'fox',
    name: 'Cáo',
    group: 'small_mammal',
    description: 'Thú săn mồi cỡ vừa tinh ranh, chuyên săn thỏ, chuột và các loài chim.',
    sizePreset: 'medium',
    diet: 'carnivore',
    habitats: [TerrainType.PLAIN, TerrainType.HILL, TerrainType.DENSE_FOREST, TerrainType.PLATEAU],
    spawnWeight: 8,
    preySpeciesIds: [
      'rabbit',
      'house_mouse',
      'field_rat',
      'squirrel',
      'chicken',
      'duck',
      'sparrow',
      'pigeon',
      'pheasant',
    ],
    lifespanYears: 12,
    adultAgeYears: 1.4,
    reproductionCooldownDays: 45,
    bodyShape: 'quadruped',
    primaryColor: '#ea580c',
    secondaryColor: '#fff7ed',
  }),
  createAnimalSpecies({
    id: 'monkey',
    name: 'Khỉ',
    group: 'small_mammal',
    description: 'Loài linh trưởng nhanh nhẹn sống ở rừng rậm và sườn núi, kiếm trái cây và hạt.',
    sizePreset: 'medium',
    diet: 'omnivore',
    habitats: [TerrainType.DENSE_FOREST, TerrainType.HILL, TerrainType.MOUNTAIN],
    spawnWeight: 9,
    lifespanYears: 18,
    adultAgeYears: 2.5,
    reproductionCooldownDays: 55,
    bodyShape: 'small_mammal',
    primaryColor: '#92400e',
    secondaryColor: '#fde68a',
  }),
];
